
name: Release

on:
  push:
    branches:
      - master

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v2
        with:
          # be careful not to include ~/.m2/settings.xml which contains credentials
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: release-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            release-m2
            ${{ runner.os }}-m2

      - name: Set up Maven settings.xml to access Sonatype Nexus
        run: |
          echo '
            <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                <server>
                  <id>ossrh</id>
                  <username>${{ secrets.SONATYPE_USER }}</username>
                  <password>${{ secrets.SONATYPE_PASSWORD }}</password>
                </server>
              </servers>
            </settings>
          ' > ~/.m2/settings.xml

      - name: Set up GPG keys
        run: |
          mkdir .gpg
          echo '${{ secrets.GPG_PRIVATE_KEY }}' > .gpg/private_key.gpg
          gpg --import .gpg/private_key.gpg
          rm -rf .gpg

      - name: Release
        run: bash mvnw -B clean deploy -DskipTests -Prelease

      - name: Detect release version
        id: get-version
        run: |
          version=$(bash mvnw initialize help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$version"

      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-conf.yml
          name: ${{ steps.get-version.outputs.version }}
          tag: R${{ steps.get-version.outputs.version }}
          version: ${{ steps.get-version.outputs.version }}
          publish: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # TODO update public code and commit changes
